#!/bin/bash
sleep 1
## export GTK2_RC_FILES="$HOME/.gtkrc-2.0" &
xrdb merge .Xresources &

## enable local fonts in .fonts directory
xset +fp /usr/share/fonts &
xset +fp /usr/share/fonts/local &
xset +fp /usr/share/fonts/misc &
xset +fp ~/.fonts &
xset fp rehash &
fc-cache -fv &

## Automount removable media
devmon &

## powersaving options
xset s off &
xset s noblank &
xset s noexpose &
xset c on &
xset -dpms &

# Cursor
xsetroot -cursor_name left_ptr &

## Repeat keys
xset r rate 350 50 &

## Touchpad natural scrolling (xinput list => xinput list-props $id)
xinput set-prop 'DELL0844:00 04F3:3074 Touchpad' 'libinput Tapping Enabled' 1
xinput set-prop 'DELL0844:00 04F3:3074 Touchpad' 'libinput Natural Scrolling Enabled' 1

## Make monitor settings persist between reboots
eval $(awk -F'=' '/Exec=/ {print $2}' ~/.config/autostart/lxrandr-autostart.desktop) &

## Map super key to trigger rofi when used alone
xcape -e 'Super_L=Super_L|Shift_L|space' &

## Polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

## Gnome keyring
gnome-keyring-daemon &

## Screensaver
gnome-screensaver &

## Network Manager applet
killall -q nm-applet
while pgrep -u $UID -x nm-applet >/dev/null; do sleep 1; done
nm-applet &

## BLUEMAN
killall -q blueman-applet
while pgrep -u $UID -x blueman-applet >/dev/null; do sleep 1; done
blueman-applet &

## PYWAL
wal --theme base16-onedark &

## IBUS
ibus-daemon -drx &

## Keybindings daemon
sxhkd &

## POLYBAR
~/.config/polybar/launch.sh &
killall redshift
dex -a -s ~/.config/autostart/ &

## Wallpaper
~/.fehbg &

## Picom
picom --experimental-backend -b &
