#!/bin/bash
. "${HOME}/.cache/wal/colors.sh" # source the colors.

#This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges
bspc config window_gap $GAP
bspc config top_padding $((PANEL_HEIGHT+PANEL_TOP_MARGIN+2*BORDER_SIZE))
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

#Various settings
bspc config gapless_monocle     false #Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config borderless_monocle  false
bspc config single_monocle true
#bspc config paddingless_monocle false
#bspc config ignore_ewmh_focus      true
bspc config initial_polarity second_child
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
## Honor size hints: do not make windows smaller than they wish to be
bspc config honor_size_hints true 

##Color settings
bspc config active_border_color "$color5"
bspc config focused_border_color "$color5"
bspc config normal_border_color "#222222"
bspc config presel_feedback_color "$color2"
bspc config border_width $BORDER_SIZE

bspc config focus_follows_pointer false

#Settings for manual splitting
bspc config split_ratio         0.5
bspc rule -a screenkey --unmanage
bspc rule -a gcolor2 state=floating center=true
bspc rule -a Lxappearance state=floating center=true
bspc rule -a gmrun state=floating center=true
bspc rule -a lxterminal state=floating center=true sticky=true
bspc rule -a viewnior state=floating center=true
bspc rule -a file-roller state=floating center=true
bspc rule -a floaterm state=floating center=true
bspc rule -a conky sticky=on manage=off lower=on
bspc rule -a astime sticky=on
bspc rule -a '*:yad' state=floating focus=on
bspc rule -a Docky layer=above border=off manage=on
bspc rule -a Plank layer=above border=off manage=on
bspc rule -a wbar layer=above
bspc rule -a dockbarx layer=above
bspc rule -a gnome-pie border=off manage=off
bspc rule -a libreoffice state=tiled
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a '*:soffice' state=tiled
bspc rule -a '*:shutter' state=floating center=true
bspc rule -a '*:eog' state=floating
bspc rule -a Gnome-disks state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Gnome-terminal state=floating
bspc rule -a discord state=tiled desktop=육
bspc rule -a Slack desktop=팔
bspc rule -a TelegramDesktop desktop=팔
bspc rule -a Skype desktop=칠
bspc rule -a GitKraken desktop=사
bspc rule -a kitty desktop=이
bspc rule -a neovide desktop=삼
bspc rule -a Google-chrome desktop=일

##  Autogap adjusts windowgap automatically according to the number of
##  windows on the desktop. Using it disables negative window gap.
#autogap &

##  This script balances all windows when new one is spawned 
#euclid_balancer &

##Edge-switcher switches to next workspace when moves moves to the 
##edge of the monitor (behavior similar to enlightenment)
#edge-switcher &

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command /usr/bin/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command /usr/bin/adjust-new-window

## This creates and names desktops for multiple monitors.
$HOME/.config/bspwm/workspaces_multimonitor &
$HOME/.config/bspwm/autostart &
